hexapod_control:
  ros__parameters:
    step_height: 0.03
    step_length: 0.08
    cycle_time: 2.0
    gait_type: "tripod"

joint_state_publisher:
  ros__parameters:
    frequency: 0.8
    amplitude: 0.3
